#!/usr/bin/env tsx
// Weekly Markdown digest of social performance.
//
// Run from GH Actions every Monday 06:00 UTC. Writes `reports/YYYY-WW.md`
// and copies it to `reports/latest.md`. The workflow then commits and pushes.

import 'dotenv/config';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { supabaseAdmin } from './lib/supabaseAdmin';

const __dirname = dirname(fileURLToPath(import.meta.url));

const REPO_ROOT = resolve(__dirname, '..', '..');
const REPORTS_DIR = resolve(REPO_ROOT, 'reports');

async function main(): Promise<void> {
  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    console.error('digest: SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY required');
    process.exit(1);
  }

  const now = new Date();
  const sevenDaysAgo = new Date(now.getTime() - 7 * 86400 * 1000);
  const since = sevenDaysAgo.toISOString();

  const { data: rows, error } = await supabaseAdmin()
    .from('post_metrics')
    .select('*')
    .gte('posted_at', since)
    .order('clicks', { ascending: false });
  if (error) {
    console.error('digest: query failed —', error.message);
    process.exit(1);
  }

  const items = (rows ?? []) as Array<{
    platform: string; product_sku: string | null; occasion: string | null;
    posted_at: string; caption: string | null; cta_src: string; clicks: number;
  }>;

  const total = items.length;
  const totalClicks = items.reduce((s, r) => s + (r.clicks ?? 0), 0);
  const byPlatform = groupBy(items, r => r.platform);
  const top = items.slice(0, 3);
  const bottom = items.slice(-3).reverse();

  const iso = now.toISOString().slice(0, 10);
  const week = isoWeek(now);
  const md = [
    `# Crafty Chocolates — social digest, week ${week} (${iso})`,
    '',
    `Window: ${since.slice(0, 10)} → ${iso}`,
    '',
    `## Totals`,
    `- Posts published: **${total}**`,
    `- wa.me clicks: **${totalClicks}**`,
    `- Click-through per post: **${total > 0 ? (totalClicks / total).toFixed(2) : '0.00'}**`,
    '',
    `## By platform`,
    ...Object.entries(byPlatform).map(([p, rs]) => {
      const c = rs.reduce((s, r) => s + (r.clicks ?? 0), 0);
      return `- **${p}** — ${rs.length} posts, ${c} clicks (avg ${(c / rs.length).toFixed(2)})`;
    }),
    '',
    `## Top 3 by clicks`,
    ...top.map((r, i) => `${i + 1}. **${r.product_sku ?? '?'}** on ${r.platform} — ${r.clicks} clicks  \n   _${(r.caption ?? '').slice(0, 140)}_`),
    '',
    `## Bottom 3 by clicks`,
    ...bottom.map((r, i) => `${i + 1}. **${r.product_sku ?? '?'}** on ${r.platform} — ${r.clicks} clicks  \n   _${(r.caption ?? '').slice(0, 140)}_`),
    '',
    `---`,
    `Generated by \`scripts/social/digest.ts\` at ${now.toISOString()}.`,
  ].join('\n');

  mkdirSync(REPORTS_DIR, { recursive: true });
  const dated = resolve(REPORTS_DIR, `${now.getUTCFullYear()}-W${String(week).padStart(2, '0')}.md`);
  const latest = resolve(REPORTS_DIR, 'latest.md');
  writeFileSync(dated, md);
  writeFileSync(latest, md);
  console.log(`digest: wrote ${dated} and ${latest}`);
}

function groupBy<T>(arr: T[], k: (t: T) => string): Record<string, T[]> {
  const out: Record<string, T[]> = {};
  for (const item of arr) {
    const key = k(item);
    (out[key] ??= []).push(item);
  }
  return out;
}

function isoWeek(d: Date): number {
  const date = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()));
  const dayNum = date.getUTCDay() || 7;
  date.setUTCDate(date.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
  return Math.ceil((((date.getTime() - yearStart.getTime()) / 86400000) + 1) / 7);
}

main().catch(err => { console.error(err); process.exit(1); });
